baseURL = 'https://happilynerdy.com/'
languageCode = 'en-us'
title = 'Happily Nerdy'
theme = 'happily-nerdy'

# Disable unused features for minimal build
disableKinds = ['taxonomy', 'term']

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[params]
  siteName = 'Happily Nerdy'
  author = 'Matt Wielbut'
  bio = 'Currently building <a href="https://openly.com">Openly</a>, a next-generation home & auto insurance company.<br><br>Previously, co-founded education technology startup Recitate and insurance startup Elements Insurance (sold in 2020 to Titan Insurance) and spent way too much time playing with graph-based semantic search (Peekful). <br><br>In a past life, VP in Engineering at <a href="https://gs.com">Goldman Sachs</a>.'

  # Social links
  github = 'mwielbut'
  linkedin = 'matt-wielbut'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
